import { buildPermissions } from "./permissions";// Generated by Zero Schema Generator

import { createSchema, definePermissions, Row, column } from "@rocicorp/zero";

const { enumeration } = column;

// Define schemas

const UserSchema = {
  tableName: "users",
  columns: {
    id: "number",
    name: "string",
  },
  primaryKey: "id",
} as const;

// Define schema

export const schema = createSchema({
  version: 1,
  tables: {
    users: UserSchema,
  },
});

// Define types
export type Schema = typeof schema;
export type User = Row<typeof UserSchema>;

// Define permissions

// Important: currently no permissions are generated so evey operation is allowed!


export const permissions = buildPermissions(schema);

// DO NOT TOUCH THIS. The schema hash is used to determine if the schema has changed and correctly update the version.
// Schema hash: 006d4a9afc21ed052d60e7e5bef251f0dd8cf61621babd6cb6368ca276bf13bb
